### ISSUE TITLE
Support for scikit-learn>=0.24

### ISSUE THREAD

**Issue by JonasRauch** [BCG-Gamma/sklearndf#165]
Current requirement is scikit-learn 0.23.x. Sklearn 0.24.* has been out since December 2020 and is becoming the default version is most environments. This incompatibility prevents us from using sklearndf.

**Comment by j-ittner** [comment]
@JonasRauch we'll get on to it next week - will ping you when done.

**Comment by j-ittner** [comment]
@JonasRauch sklearndf 1.2 is out with support for scikit-learn 0.24. Let us know how it works for you!
